### ISSUE TITLE
[Analysis] Add spatial index on the_geom_webmercator

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#201]
Probably worthy to explore BRIN as an alternative to GIST index used by CDB_CartodbfyTable.

Depends on #200.

**Comment by javisantana** [comment]
I think that adding a `order by st_geohash(the_geom_webmercator)` and then `create index on temp_table using brin(the_geom_webmercator)` would help

Not sure if intermediate tables should add the index on the_geom so following analysis use that index

**Comment by javisantana** [comment]
it depends on postgis 2.3 of course :)

**Comment by rafatower** [comment]
Blocked by https://github.com/CartoDB/camshaft/issues/200

**Comment by rochoa** [comment]
@javisantana and I were discussing if we really need to create `the_geom_webmercator` column. We should evaluate what is the performance advantage and the trade-offs of having two geometry columns and two indexes now that we have complex analyses that only rely on `the_geom` and at some point, you want to render based on `the_geom_webmercator`.

**Comment by javisantana** [comment]
There are two things:

1) analysis tables where obviously having two columns is a waste of space and computing power 
2) rendering where the_geom_webmercator could help because we don't have to actually transform it. I made a proposal some time ago to keep the_geom_webmercator ready to be rendered from zoom level 0 to 17 and use the_geom after 17. We could store if using MVT format but it would still need geospatial index and storage. I think it worths a benchmark cc @rafatower

**Comment by ethervoid** [comment]
Just to point something, the tiler uses `the_geom_webmercator` to filter:

```sql
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(16028529.52865979 -4370984.580088057,16030994.62282198 -4368519.485925857)'::box3d, 3857);
```

so I think it worths to have the column populated and indexed to improve the performance
