### ISSUE TITLE
DO Analysis fails in table if source table has a column called "id"

### ISSUE THREAD

**Issue by talos** [CartoDB/camshaft#264]
### Steps to reproduce

1. Create a blank table
2. Add a point
3. Rename the `description` column to be called `id`
3. Try to augment from DO

### What happens

Endless spinning, no data!

### .carto file

[untitled_table_41 map (on 2017-02-22 at 22.05.33).zip](https://github.com/CartoDB/camshaft/files/794950/untitled_table_41.map.on.2017-02-22.at.22.05.33.zip)

**Comment by andrewbt** [comment]
FYI @bspiro this is why starbucks data observatory demo hasn't worked this week - I will get you a new starbucks dataset that works (or you can just drop your's "id" column), but we should fix this bug in production soon too.

FYI @danicarrion we should try and get this bugfix prioritized because it affects the starbucks demo dataset and we use that one a lot with DO on meetings with clients! :-O

**Comment by talos** [comment]
PR is open.

**Comment by danicarrion** [comment]
thanks!
